name: GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: --enable-index-page -Zunstable-options
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - uses: actions-rs/cargo@v1
      with:
        toolchain: nightly
        command: doc
        args: --workspace
    - uses: actions/upload-pages-artifact@v4
      with:
        path: target/doc
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
